CREATE TABLE PRICES (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DECIMAL,
    CURR VARCHAR(255),
    PRIMARY KEY (PRICE_LIST, PRODUCT_ID),
    FOREIGN KEY (BRAND_ID) references BRANDS(BRAND_ID)
);
